[build]
  # Build command for the frontend
  command = "npm run build:frontend"
  
  # Directory to publish (frontend build output)
  publish = "thunder/frontend/dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Force npm to install optional dependencies
  NPM_FLAGS = "--include=optional"
  # Disable npm audit during build for faster builds
  NPM_CONFIG_AUDIT = "false"
  # Use npm ci for faster, reliable builds
  NPM_CONFIG_PREFER_OFFLINE = "true"

# Build settings for different contexts
[context.production]
  command = "npm run build:frontend"
  publish = "thunder/frontend/dist"

[context.deploy-preview]
  command = "npm run build:frontend"
  publish = "thunder/frontend/dist"

[context.branch-deploy]
  command = "npm run build:frontend"
  publish = "thunder/frontend/dist"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions directory (for future serverless functions)
[functions]
  directory = "netlify/functions"
